### ISSUE TITLE
Package not returning the same meta data as Laravel

### ISSUE THREAD

**Issue by tychovbh** [chelout/laravel-offset-pagination#4]
Great package! But it doesn't return the same information as Laravel does with pagination. I'm missing:

current_page: 1
from: 1
last_page: 150
path: "http://localhost/users"
per_page: 12
to: 12

My program expects these variables because sometimes i use offset and sometimes the normal pagination.

Can this be fixed?

**Comment by chelout** [comment]
Thanks!
There are no plans to change format.
